name: Dev Deploy branch

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy serverless virus scan
    runs-on: ubuntu-latest
    env:
        environment: dev    
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ env.AWS_ROLE_ARN }}
        aws-region: eu-west-2
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2   
      
    - name: Checkout the latest master		  
      uses: actions/checkout@v3      
      
    - name: Build Docker layer for Lambda
      uses: docker/build-push-action@v3
      with:
        context: .
        push: false
        tags: clamav:latest

    - name: Serverless deploy
      uses: serverless/github-action@v3.1
      with:
        args: deploy
      env:
        stage: dev