name: Dev Deploy branch

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy serverless virus scan
    runs-on: ubuntu-latest
    environment: dev    
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - name: Echo
      run: echo ${{ secrets.AWS_ROLE_ARN }} | echo ${{ secrets.AWS_REGION }}
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Serverless Framework
      run: npm install -g serverless
    
    - name: Checkout the latest master		  
      uses: actions/checkout@v3      
      
    - name: Build Docker layer for Lambda
      run: docker build -t clamav .

    - name: Serverless deploy
      run: serverless deploy --stage dev --region ${{ secrets.AWS_REGION }}