name: Dev Deploy branch

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy serverless virus scan
    runs-on: ubuntu-latest
    environment: dev    
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::846769538626:role/IAM_Admin_Role
        aws-region: eu-west-2
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Serverless Framework
      run: npm install -g serverless
    
    - name: Checkout the latest master		  
      uses: actions/checkout@v3      
      
    - name: Build Docker layer for Lambda
      run: docker build -t clamav .

    - name: Serverless deploy
      run: serverless deploy --stage dev --region eu-west-2